"""
CalculiX Input Deck Generator (.inp file writer).

Produces a complete CalculiX static analysis input file:

    *NODE          — all mesh nodes
    *ELEMENT       — C3D4 / C3D10 tetrahedral elements
    *MATERIAL      — elastic isotropic from MaterialLibrary
    *SOLID SECTION — assigns material to element set
    *BOUNDARY      — fixed DOFs on BC nodes
    *CLOAD         — concentrated forces on load nodes
    *STEP          — static analysis step
    *NODE FILE     — request U (displacement) output
    *EL FILE       — request S (stress) output
    *END STEP

All coordinates in mm, forces in N, modulus in MPa → stress in MPa.
"""
import logging
from pathlib import Path
from typing import Any

from models.materials import MaterialLibrary
from models.specification import DesignSpecification, LoadDirection

logger = logging.getLogger(__name__)


# ─── DOF direction map ───────────────────────────────────────────────────────

_DIR_TO_DOFS: dict[str, tuple[int, float]] = {
    LoadDirection.POSITIVE_X: (1, +1.0),
    LoadDirection.NEGATIVE_X: (1, -1.0),
    LoadDirection.POSITIVE_Y: (2, +1.0),
    LoadDirection.NEGATIVE_Y: (2, -1.0),
    LoadDirection.POSITIVE_Z: (3, +1.0),
    LoadDirection.NEGATIVE_Z: (3, -1.0),
}


def _dof_and_sign(direction: LoadDirection) -> tuple[int, float]:
    """Return (dof_index, sign) for a LoadDirection enum value."""
    return _DIR_TO_DOFS.get(direction, (2, -1.0))


# ─── Main Generator ──────────────────────────────────────────────────────────

class InpGenerator:
    """
    Generates a CalculiX .inp input file from mesh data and a design spec.

    Parameters
    ----------
    mesh_data   : dict returned by GmshMesher.mesh()
    spec        : DesignSpecification
    output_dir  : directory to write the .inp file
    job_name    : base name for the job (default: "fea_job")
    """

    def __init__(
        self,
        mesh_data: dict[str, Any],
        spec: DesignSpecification,
        output_dir: Path,
        job_name: str = "fea_job",
    ):
        self.mesh_data = mesh_data
        self.spec = spec
        self.output_dir = Path(output_dir)
        self.job_name = job_name
        self.inp_path = self.output_dir / f"{job_name}.inp"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ─── Public API ──────────────────────────────────────────────────────────

    def write(self) -> Path:
        """Write the .inp file and return its path."""
        material = MaterialLibrary.get(self.spec.material_name)
        nodes    = self.mesh_data["nodes"]
        elements = self.mesh_data["elements"]
        bc_nodes = self.mesh_data["bc_nodes"]
        load_nodes = self.mesh_data["load_nodes"]

        # Detect element type
        sample_elem = next(iter(elements.values()))
        npe = len(sample_elem)
        if npe == 4:
            elem_type = "C3D4"
        elif npe == 10:
            elem_type = "C3D10"
        else:
            elem_type = f"C3D{npe}"
            logger.warning("Unexpected nodes-per-element: %d → using %s", npe, elem_type)

        logger.info("Writing CalculiX input: %s  (%d nodes, %d elements, type=%s)",
                    self.inp_path, len(nodes), len(elements), elem_type)

        lines: list[str] = []
        _w = lines.append

        # ── Header ───────────────────────────────────────────────────────────
        _w(f"** CalculiX Input Deck — Agentic CAD Pipeline")
        _w(f"** Component : {self.spec.component.value}")
        _w(f"** Material  : {material.display_name}")
        _w(f"** Generated by: backend/fea/inp_generator.py")
        _w("")

        # ── Nodes ────────────────────────────────────────────────────────────
        _w("*NODE, NSET=NALL")
        for nid, (x, y, z) in sorted(nodes.items()):
            _w(f"{nid}, {x:.6f}, {y:.6f}, {z:.6f}")
        _w("")

        # ── Elements ─────────────────────────────────────────────────────────
        _w(f"*ELEMENT, TYPE={elem_type}, ELSET=EALL")
        for eid, conn in sorted(elements.items()):
            conn_str = ", ".join(str(n) for n in conn)
            _w(f"{eid}, {conn_str}")
        _w("")

        # ── Node Sets ────────────────────────────────────────────────────────
        _w("** Boundary condition nodes")
        _w("*NSET, NSET=BC_NODES")
        _write_node_set(lines, sorted(bc_nodes))

        _w("** Load application nodes")
        _w("*NSET, NSET=LOAD_NODES")
        _write_node_set(lines, sorted(load_nodes))
        _w("")

        # ── Material ─────────────────────────────────────────────────────────
        _w(f"** Material: {material.display_name}")
        _w(f"*MATERIAL, NAME={material.name.upper()}")
        _w("*ELASTIC")
        _w(f"{material.youngs_modulus_mpa:.1f}, {material.poisson_ratio}")
        _w("*DENSITY")
        # CalculiX density in consistent units: tonne/mm³ when mm+N+MPa
        density_t_mm3 = material.density_kg_m3 * 1e-12  # kg/m³ → t/mm³
        _w(f"{density_t_mm3:.4e}")
        _w("")

        # ── Solid Section ────────────────────────────────────────────────────
        _w("*SOLID SECTION, ELSET=EALL, MATERIAL=" + material.name.upper())
        _w("")

        # ── Step: Static ─────────────────────────────────────────────────────
        _w("*STEP, NLGEOM=NO, INC=100")
        _w("*STATIC")
        _w("1.0, 1.0, 1e-5, 1.0")
        _w("")

        # ── Boundary Conditions ───────────────────────────────────────────────
        _w("** Fixed boundary conditions (all DOFs = 0)")
        _w("*BOUNDARY")
        for nid in sorted(bc_nodes):
            _w(f"{nid}, 1, 3, 0.0")   # DOF 1,2,3 (UX, UY, UZ) = 0
        _w("")

        # ── Loads ─────────────────────────────────────────────────────────────
        if load_nodes:
            _w("** Distributed load over load nodes")
            _w("*CLOAD")
            n_load = len(load_nodes)
            for load in self.spec.loads:
                dof, sign = _dof_and_sign(load.direction)
                force_per_node = sign * load.magnitude / max(n_load, 1)
                for nid in sorted(load_nodes):
                    _w(f"{nid}, {dof}, {force_per_node:.6f}")
            _w("")
        else:
            logger.warning("No load nodes found — applying unit load to all nodes.")
            _w("*CLOAD")
            total_load = sum(ld.magnitude for ld in self.spec.loads)
            n_total = len(nodes)
            for nid in sorted(nodes.keys()):
                _w(f"{nid}, 2, {-total_load / n_total:.6f}")
            _w("")

        # ── Output Requests ───────────────────────────────────────────────────
        _w("** Output: Displacement (U) and Stress (S)")
        _w("*NODE FILE")
        _w("U")
        _w("*EL FILE")
        _w("S, EVOL")
        _w("*NODE PRINT, NSET=NALL")
        _w("U")
        _w("*EL PRINT, ELSET=EALL")
        _w("S")
        _w("")

        # ── End Step ─────────────────────────────────────────────────────────
        _w("*END STEP")

        # Write file
        with open(self.inp_path, "w") as f:
            f.write("\n".join(lines))

        logger.info("CalculiX .inp written: %s", self.inp_path)
        return self.inp_path


# ─── Helper ──────────────────────────────────────────────────────────────────

def _write_node_set(lines: list[str], sorted_ids: list[int], per_line: int = 16) -> None:
    """Write node IDs in CalculiX format (max 16 per line)."""
    for i in range(0, len(sorted_ids), per_line):
        chunk = sorted_ids[i : i + per_line]
        lines.append(", ".join(str(n) for n in chunk))
