"""
FEA Pipeline — top-level orchestrator for Phase 4.

Chains:
    1. GmshMesher       → mesh data (nodes, elements, load/BC node sets)
    2. InpGenerator     → writes CalculiX .inp input deck
    3. CalculiXSolver   → runs ccx (or Python fallback)
    4. FRDParser        → parses .frd / .dat result files
    5. FEAAnalyzer      → computes FEAResult + constraint checks

Usage:
    from fea.pipeline import run_fea_pipeline
    result = run_fea_pipeline(spec, step_path, output_dir, ccx_path)
"""
import logging
import uuid
from pathlib import Path
from typing import Any

from models.results import FEAResult, ConstraintCheck
from models.specification import DesignSpecification
from config import CCX_PATH, FEA_OUTPUT_DIR, MESH_OUTPUT_DIR

from .mesher import GmshMesher
from .inp_generator import InpGenerator
from .solver import CalculiXSolver
from .result_parser import FRDParser
from .analyzer import FEAAnalyzer

logger = logging.getLogger(__name__)


def run_fea_pipeline(
    spec: DesignSpecification,
    step_path: Path,
    output_dir: Path | None = None,
    ccx_path: Path | None = None,
    job_id: str | None = None,
) -> dict[str, Any]:
    """
    Run the complete FEA pipeline on a CAD model.

    Parameters
    ----------
    spec        : Validated DesignSpecification
    step_path   : Path to the STEP file generated by Phase 3
    output_dir  : Directory for mesh + FEA files (default: config.FEA_OUTPUT_DIR)
    ccx_path    : Path to CalculiX binary (default: config.CCX_PATH)
    job_id      : Unique job identifier (auto-generated if None)

    Returns
    -------
    dict with:
        fea_result       : FEAResult
        constraint_checks: list[ConstraintCheck]
        all_passed       : bool
        mesh_data        : dict (nodes, elements, paths)
        solver_info      : dict (solver_mode, solver_time)
        inp_path         : str
        frd_path         : str | None
    """
    if job_id is None:
        job_id = uuid.uuid4().hex[:8]

    if output_dir is None:
        output_dir = FEA_OUTPUT_DIR

    if ccx_path is None:
        ccx_path = CCX_PATH

    job_dir = Path(output_dir) / job_id
    job_dir.mkdir(parents=True, exist_ok=True)
    mesh_dir = Path(MESH_OUTPUT_DIR) / job_id
    mesh_dir.mkdir(parents=True, exist_ok=True)

    logger.info("=" * 60)
    logger.info("FEA Pipeline START  job_id=%s", job_id)
    logger.info("  STEP  : %s", step_path)
    logger.info("  Output: %s", job_dir)
    logger.info("=" * 60)

    # ── Extract load/BC location strings ────────────────────────────────────
    load_locations = [ld.location for ld in spec.loads]
    bc_locations   = [bc.location for bc in spec.boundary_conditions]

    logger.info("Load locations : %s", load_locations)
    logger.info("BC locations   : %s", bc_locations)

    # ── Step 1: Mesh ─────────────────────────────────────────────────────────
    logger.info("Step 1/5: Meshing with Gmsh…")
    mesher = GmshMesher(
        step_path=step_path,
        output_dir=mesh_dir,
        element_size=spec.mesh_settings.element_size,
        element_order=spec.mesh_settings.element_order,
    )
    mesh_data = mesher.mesh(
        load_locations=load_locations,
        bc_locations=bc_locations,
    )
    logger.info("  ✓ Mesh: %d nodes, %d elements", mesh_data["num_nodes"], mesh_data["num_elements"])

    # ── Step 2: Write .inp ───────────────────────────────────────────────────
    logger.info("Step 2/5: Writing CalculiX .inp file…")
    inp_gen = InpGenerator(
        mesh_data=mesh_data,
        spec=spec,
        output_dir=job_dir,
        job_name="fea_job",
    )
    inp_path = inp_gen.write()
    logger.info("  ✓ .inp written: %s", inp_path)

    # ── Step 3: Run solver ───────────────────────────────────────────────────
    logger.info("Step 3/5: Running solver (CalculiX or fallback)…")
    solver = CalculiXSolver(
        ccx_path=ccx_path,
        fea_dir=job_dir,
        job_name="fea_job",
        timeout_sec=600,
    )
    solver_info = solver.run()
    logger.info(
        "  ✓ Solver done: mode=%s, time=%.1f s",
        solver_info["solver_mode"], solver_info["solver_time"],
    )

    # ── Step 4: Parse results ────────────────────────────────────────────────
    logger.info("Step 4/5: Parsing results…")
    parser = FRDParser(
        frd_path=solver_info["frd_path"],
        dat_path=solver_info.get("dat_path"),
    )
    parsed_data = parser.parse()
    logger.info(
        "  ✓ Parsed: max_disp=%.4f mm, max_stress=%.2f MPa",
        parsed_data["max_displacement_mm"], parsed_data["max_stress_mpa"],
    )

    # ── Step 5: Analyze ──────────────────────────────────────────────────────
    logger.info("Step 5/5: Analyzing results…")
    analyzer = FEAAnalyzer(
        parsed_data=parsed_data,
        mesh_data=mesh_data,
        solver_info=solver_info,
        spec=spec,
    )
    fea_result: FEAResult = analyzer.analyze()
    constraint_checks: list[ConstraintCheck] = analyzer.check_constraints(fea_result)
    all_passed = all(c.passed for c in constraint_checks)

    logger.info("=" * 60)
    logger.info("FEA Pipeline COMPLETE")
    logger.info("  max_stress     = %.2f MPa", fea_result.max_stress_mpa)
    logger.info("  max_disp       = %.4f mm",  fea_result.max_displacement_mm)
    logger.info("  safety_factor  = %.2f",      fea_result.safety_factor)
    logger.info("  mass           = %.4f kg",   fea_result.mass_kg)
    logger.info("  constraints    = %s", "✓ ALL PASSED" if all_passed else "✗ FAILED")
    logger.info("=" * 60)

    return {
        "fea_result": fea_result,
        "constraint_checks": constraint_checks,
        "all_passed": all_passed,
        "mesh_data": {
            "num_nodes": mesh_data["num_nodes"],
            "num_elements": mesh_data["num_elements"],
            "mesh_path": mesh_data["mesh_path"],
        },
        "solver_info": {
            "solver_mode": solver_info["solver_mode"],
            "solver_time": solver_info["solver_time"],
        },
        "inp_path": str(inp_path),
        "frd_path": solver_info.get("frd_path"),
        "job_id": job_id,
    }
